### ISSUE TITLE
运行时可能会被 mirai 服务器断开连接

### ISSUE THREAD

**Issue by PigeonYuze** [PigeonYuze/GroupBotSuffix#11]
### 问题描述

当改名较为频繁时，可能会被 mirai 服务器断开连接，并将 Bot 下线(会自动重连)

### 如何复现？
使用如下配置:
- 每一波改名间隔 1 分钟
- 每一次改名 **间隔小于1分钟 如 `200ms`**

并将更改名称功能在多个群聊(**大于等于 5 个群聊**)中开启

符合调节时，可能会有以下控制台输出
_(LoggingConfig: Bot 输出: `ALL`)_
```
Time 15:36:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:36:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:36:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:36:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:36:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:36:37 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:36 Bot/xx: Event: MemberCardChangeEvent(...)
Time 15:37:37 Bot/xx: Event: MemberCardChangeEvent(...)
```

经过长时间的运行后，您的 Bot 账号可能会被 服务器 **强制下线**

这大概率是因为频繁且有规律的请求，被 mirai 服务器 当成了 `DNS` 攻击

最后被踢出服务器并下线：
```
Time xx:xx:xx Bot/xx **Event: BotOfflineEvent.MsgOffline**(...)
```
*注：`BotOfflineEvent.MsgOffline` 为 `Bot` 被服务器断开连接*

### 临时的解决办法

增加每一次的更改群名间隔并使用 `Lazy Mode`

**Comment by PigeonYuze** [comment]
此 `bug` 不会修复，但是会增加新的运行方式（惰性修改群名）和检测选项是否是“可疑的”

**Comment by Initial-heart-1** [comment]
请教一下，有些疑问：
您所述 `mirai 服务器` 是否指 **腾讯 QQ 服务器**？没理解错的话 mirai 本体在使用过程中默认情况 **应当不会** 与 mamoe 的服务器直接进行通讯啊？
另 `DNS 攻击` 是否指 **DoS 攻击**？
或者上述名词有其他含义？请指明，不是特别理解😂
