### ISSUE TITLE
倒计时时间计算问题

### ISSUE THREAD

**Issue by DannyLI0319** [PigeonYuze/GroupBotSuffix#8]
如图，本来倒计时还有43分钟， 然后变成44分钟， 然后变成45分钟。。

![V J`~MOG_{R%GRFU(AJ3P5F](https://user-images.githubusercontent.com/120266145/224482541-82a2ec58-99e4-4eb7-a82a-80a7ae6b6a7a.jpg)

**Comment by DannyLI0319** [comment]
看了下，在这个文档里：
GroupBotSuffix/src/main/kotlin/execute/TimeData.kt
Line 42-49的逻辑判断有些问题：
![image](https://user-images.githubusercontent.com/120266145/224482848-adbb8db2-967c-4bf6-bf9b-a57f7f9ffafd.png)
条件是ifTrue(nowYear > objYear)
当现在的年份和目标年份相同时，这个条件的结果是False，所以相关语句不会执行

**Comment by DannyLI0319** [comment]
大佬，提供一种思路供你参考：
```kotlin
import java.time.Duration
import java.time.LocalDateTime

fun main() {
    val nowLocalDateTime = LocalDateTime.now()
    val objLocalDateTime = LocalDateTime.parse("2023-5-16T09:00:00")

    val diff = Duration.between(nowLocalDateTime, objLocalDateTime)
    val days = diff.toDays()
    val hours = diff.toHours() % 24
    val minutes = diff.toMinutes() % 60

    println("${days}天${hours}小时${minutes}分钟")
}
```

附上一些备注解释：
首先，需要定义两个 `LocalDateTime` 变量 `nowLocalDateTime` 和 `objLocalDateTime` 分别表示起始时间和结束时间。可以使用如下代码创建这两个变量：

```kotlin
val nowLocalDateTime = LocalDateTime.now()
val objLocalDateTime = LocalDateTime.parse("2023-5-16T09:00:00")
```

其中，第一行代码获取当前时间作为起始时间，第二行代码使用 `parse` 方法解析一个字符串来创建结束时间。

然后，需要计算从起始时间到结束时间相差了多少天、多少小时和多少分钟。可以使用以下代码计算：

```kotlin
val diff = Duration.between(nowLocalDateTime, objLocalDateTime)
val days = diff.toDays()
val hours = diff.toHours() % 24
val minutes = diff.toMinutes() % 60
```

其中，第一行代码使用 `between` 方法计算两个时间之间的差值，返回一个 `Duration` 对象。第二行代码调用 `toDays` 方法获取相差的天数。第三行代码使用 `%` 运算符对总小时数取模并得到不足一天的小时数。最后一行代码也是使用 `%` 运算符对总分钟数取模得到不足一小时的分钟数。

最终，可以将计算结果以某种格式输出，例如：

```kotlin
println("${days}天${hours}小时${minutes}分钟")
```

**Comment by PigeonYuze** [comment]
十分感谢，已修复
